# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            The Coding State of Mind
tagline:          Link between Creativity and Code
url:              munk801@github.io
paginate:         1
baseurl:          /
author:
  name:           Stephen Lu
  url:            https://twitter.com/StephenMunkLu
  email:          munk801@gmail.com

About: '/about'
Archive: '/archive'

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/Munk801

