markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Stephen Lu
url: munk801.github.io
description: The start to something big!
twitter: StephenMunkLu
github: Munk801
instagram: munkaliciouz
gravatar_url: http://www.gravatar.com/avatar/9b96dbfa235cbf3aa0e30035654a5a06 
